# Generated by Django 4.2.5 on 2023-09-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationattempt",
            name="passphrase",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
