# Generated by Django 4.2.5 on 2023-09-13 15:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_verificationattempt_verifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationattempt",
            name="message_delivery_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="verificationattempt",
            name="passphrase",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="verificationattempt",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
