# Generated by Django 5.0.3 on 2025-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_verificationattempt_message_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
