# Generated by Django 4.2.5 on 2023-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_verificationattempt_message_delivery_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        default="Provide the following passphrase to IT Service desk: {{passphrase}}"
                    ),
                ),
                (
                    "passphrase_length",
                    models.IntegerField(
                        default=4,
                        verbose_name="Length of the passphrase to use for verification",
                    ),
                ),
                (
                    "twilio_account_sid",
                    models.CharField(
                        default="",
                        max_length=50,
                        verbose_name="Twilio Account SID (for SMS)",
                    ),
                ),
                (
                    "twilio_auth_token",
                    models.CharField(
                        default="",
                        max_length=50,
                        verbose_name="Twilio Auth Token (for SMS)",
                    ),
                ),
                (
                    "twilio_messaging_service_sid",
                    models.CharField(
                        max_length=50,
                        verbose_name="Twilio Messaging Service SID (for SMS)",
                    ),
                ),
                (
                    "ethos_api_key",
                    models.CharField(
                        max_length=50,
                        verbose_name="Ethos API Key (for an Ethos Integrate App Registration with persons graphql resource)",
                    ),
                ),
            ],
        ),
    ]
