# Generated by Django 5.0.3 on 2025-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_verificationattempt_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
